### ISSUE TITLE
syntax highlight, code completion and auto-suggest is not working in vs-code

### ISSUE THREAD

**Issue by shivling1254** [marklogic/mlxprs#103]
Hi,

I installed the latest "MarkLogic developer tools" vs code extension.  after installing this extension I am expecting that syntax highlight, code completion, and auto-suggest should work in vs-code but it is not. Please see the below screenshot.

MarkLogic version is - 10.0-8.1

![image](https://user-images.githubusercontent.com/34579212/153759731-0f91535d-773c-4c2d-9c17-6f21d729204b.png)

syntax highlight, code completion and auto-suggest  started working after renaming .sjs to .mjs. but I don't want to do this.

is there any way to make this work with .sjs?

**Comment by brent-hartwig** [comment]
Hi, Shivling,

Please try associating the MJS and SJS file extensions to JavaScript.  Below are the associated entries from my settings.json.  The API extension is associated to JSON as MarkLogic Data Services include such files.  If you prefer the UI for changing settings, filter by "file associations" to find quickly.

```
  "files.associations": {
    "*.sjs": "javascript",
    "*.mjs": "javascript",
    "*.api": "json"
  },
```

**Comment by shivling1254** [comment]
@brent-hartwig you made my day, it is working now.

Thank you.
