### ISSUE TITLE
Connecting to https with custom CA

### ISSUE THREAD

**Issue by grtjn** [marklogic/mlxprs#105]
Has anyone been able to connect to an https app server with a server certificate signed by a company CA? I have had no luck. I get error messages like:

{ "code": "UNABLE_TO_VERIFY_LEAF_SIGNATURE" }

I am using inline comment like this:

(: mlxprs:settings
{
  "host": "testserver",
  "port": 10100,
  "contentDb": "database",
  "modulesDb": "Modules",
  "user": "admin",
  "pwd": "admin",
  "note": "These settings are for testing only",
  "ssl": true,
  "rejectUnauthorized": true,
  "pathToCa": "C:\\Users\\josten\\Projects\\datahub\\ca-bundle.crt"
}
:)

**Comment by mitchshepherd** [comment]
@grtjn Just checking, is this still an issue for you?

**Comment by BillFarber** [comment]
I have performed manual testing and setting the "pathToCa" via an inline comment like the one above.
Based on my testing, the configuration override works for the "MarkLogic: Eval <language>" commands.
However, it is not implemented for the debugger commands such as the "Evaluate Current XQuery Module" launch configuration.

**Comment by grtjn** [comment]
(facepalm) It just hit me, you need to use forward slashes, or use double backslashes. Thanks for looking into it!
