### ISSUE TITLE
Update contributing.md to describe how to build and test locally

### ISSUE THREAD

**Issue by rjrudin** [marklogic/mlxprs#107]
The current CONTRIBUTING.md file only describes how to submit a pull request. What we need are instructions for the following:

1. How to build and test the plugin locally in VSCode
2. How to run the tests (which I assume should include what's at ./client/test and at ./server/test

The above will allow any developer to review/approve future PR's by manually testing the plugin locally. And we can soon get a Jenkins build together for running the automated tests on every PR and on the `develop` branch when it's updated. 

For bonus points - include some info about what the "client" and "server" folders are for, in particular the latter - I wasn't expecting to see a "server" folder in a VSCode plugin.

**Comment by bshalke** [comment]
My understanding of server is that it's the language server used to do syntax highlighting.  I'll take a crack at this.
