### ISSUE TITLE
Eval results appear to be cached and not accurate?

### ISSUE THREAD

**Issue by tternquist** [marklogic/mlxprs#11]
I can't pin down the exact way to reproduce this, but rather frequently I find that the result of a JS eval does not appear to update the results pane, even after saving the sjs file with changes

**Comment by mikrovvelle** [comment]
This seems closely related to #10 and some problems with the async DocumentProvider in VS Code.

I've experienced it a few times as well. The easiest workaround is to close the results pane and re-run the query. This will open a new results window and a fresh cache.

**Comment by BillFarber** [comment]
Since #10 has been fixed and I have not seen this in my testing, I am closing it.

Feel free to create a new issue if you see something actionable.
