### ISSUE TITLE
Document how to run client tests via command line

### ISSUE THREAD

**Issue by rjrudin** [marklogic/mlxprs#114]
The CONTRIBUTING.md file describes how to run the client tests via the Run/Debug tool in VSCode. That's helpful for local testing. But we need instructions for running them via the command line so that we can setup a Jenkins job to run all the tests. 

Currently, running either `npm test` or `npm run-script test` results in the following error:

    Error: Cannot find module '/Users/rrudin/workspace/mlxprs/client/out/test/runTest.js'

If the above commands are correct, then the scope of this ticket is fixing the config so that the above commands work and also update the CONTRIBUTING.md file to describe how to run the tests.

Also, I've only called attention to the client tests - I'm assuming we'd want the same instructions for the server tests too.

**Comment by mitchshepherd** [comment]
Addressed in the 3.6.0 release
