### ISSUE TITLE
Circular JSON structure error when running eval

### ISSUE THREAD

**Issue by bshalke** [marklogic/mlxprs#117]
When running eval against a server for the first time, the following error is thrown:

> rejected promise not handled within 1 second: TypeError: Converting circular structure to JSON
>     --> starting at object with constructor 'Socket'
>     |     property 'parser' -> object with constructor 'HTTPParser'
>     --- property 'socket' closes the circle
> c:\Users\bshal\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96
> stack trace: TypeError: Converting circular structure to JSON
>     --> starting at object with constructor 'Socket'
>     |     property 'parser' -> object with constructor 'HTTPParser'
>     --- property 'socket' closes the circle
>     at JSON.stringify (<anonymous>)

This doesn't seem to affect the execution of the eval, but it should be cleaned up.

**Comment by mitchshepherd** [comment]
Addressed in MLXPRS 3.6.0 release
