### ISSUE TITLE
File Associations for MJS and SJS

### ISSUE THREAD

**Issue by awanczowski** [marklogic/mlxprs#119]
By default MJS and SJS should have the correct formatter associated with the file types.

**Comment by bshalke** [comment]
This can be done quickly/simply with [the languages contribution point in the config](https://code.visualstudio.com/api/references/contribution-points#contributes.languages)
I'll assign this to myself and take a look this week.

**Comment by bshalke** [comment]
I added SJS only, as MJS is already associated (at least on my install).  I think the node package is responsible for that - not sure if we want to add it explicitly or if that will cause problems with the node package.

**Comment by bshalke** [comment]
Since the PR was merged, I'm going to close the issue.
