### ISSUE TITLE
please add XQuery debugging feature

### ISSUE THREAD

**Issue by kkrolikowska** [marklogic/mlxprs#12]
please add XQuery debugging feature to mlxprs

**Comment by mikrovvelle** [comment]
@cathy1721 Should be rolling out to the marketplace any minute. Let's have a call to demo it.

**Comment by kkrolikowska** [comment]
> @cathy1721 Should be rolling out to the marketplace any minute. Let's have a call to demo it.

Thank you! I will setup a call with other developers and kindly ask for a demo of the debugging feature.
