### ISSUE TITLE
Human-readable query plans

### ISSUE THREAD

**Issue by jmakeig** [marklogic/mlxprs#14]
As a developer tuning queries, I’d like a simpler way to interpret what the database is doing under-the-covers to help me optimize my code.

MarkLogic provides various query plan reports. They provide low-level details of resource usage and optimization strategies. This information is precise and expansive, but difficult for a human to interpret, especially one without deep MarkLogic expertise. We should provide a visual summary of this information that progressively reveals the details for learning and tuning.

**Comment by jmakeig** [comment]
See also https://github.com/jpcs/queryplan-viewer

**Comment by jmakeig** [comment]
Priority:

1. Optic
1. SQL
1. SPARQL
1. CTS

(Note that the implementation for the first three is the same. They’re likely to be called in different contexts, though.)

**Comment by jmakeig** [comment]
What can be done today with existing the existing plan APIs? Could this be implemented solely on the client-side? How would we reflect actual cost calculations? Is there “longitudinal” data about past (or future?) optimizations that we could use going forward?

**Comment by jmakeig** [comment]
Ping @jpcs.

**Comment by rjrudin** [comment]
Will consider this first in the context of the server
