### ISSUE TITLE
Plan to add JS debugger  

### ISSUE THREAD

**Issue by zzzwan** [marklogic/mlxprs#15]
Planning to add JS debugger functionality into mlxprs. 
My current plan is to put debugger related files inside a folder named "JSDebugger" under folder client. 
Existing files that will be affected are: 
client/extension.ts -- In activate() functions, push debugConfigurationProvider and DebugAdapterDescriptorFactory.
webpack.config.js -- adds one more entry JSDebug for the debug adapter.
package.json -- adds new contributes "breakpoints" and "debugger" and dependencies.

Please advise on where to put the debugger files in the project.

**Comment by mikrovvelle** [comment]
Your current plan sounds fine. Can you open a pull request?

**Comment by mikrovvelle** [comment]
I think we can close this now that we have a plan and we've got the PR on the `sjsdbg` branch here. I'll track newer developments in the newer issues as they come in.
