### ISSUE TITLE
Pre-wire known Data Hub configuration schemas

### ISSUE THREAD

**Issue by jmakeig** [marklogic/mlxprs#16]

**Comment by jmakeig** [comment]
For example, https://code.visualstudio.com/api/references/contribution-points#contributes.jsonValidation

**Comment by mikrovvelle** [comment]
This will need to wait for https://github.com/marklogic/datahub-central/issues/430, right? I think I'd be reverse-engineering the schemas myself otherwise.

**Comment by jmakeig** [comment]
`fn:true()`

**Comment by mikrovvelle** [comment]
XQuery from Justin? Oh my
