### ISSUE TITLE
Plan to add support for streaming module files for JS debugger

### ISSUE THREAD

**Issue by zzzwan** [marklogic/mlxprs#20]
Currently the debug adapter does not work if user have no access for the imported modules. The plan is to ask MarkLogic server to stream back the module file and display it as a local temporary file for user to view and debug

**Comment by jmakeig** [comment]
Part of #26

**Comment by jmakeig** [comment]
We should expect the debug user to have a local copy of the source code that she’s debugging remotely, such as deployed today by ml-gradle, e.g. https://github.com/marklogic-community/ml-gradle/tree/master/examples/data-services/src/main/ml-modules/root/helloWorld. We need to gracefully handle the case where the local copy is out of sync with what MarkLogic is running. However, I propose that we don’t need to assume that they might not have the source at all. 

In particular, when a user finds a bug in their debugging activities, I’d expect them to 

1. Stop the debugging session
2. Change the code in situ
3. Redeploy to MarkLogic (probably automatically using [ml-gradle’s watch functionality](https://github.com/marklogic-community/ml-gradle/wiki/Watching-for-module-changes))
4. Kick off another debugging session (hopefully via a test that tickles the bug in question) 

Based on my early experience, that mostly works today in v2.0.0.
