### ISSUE TITLE
Auto-suggest, code completion for XQuery

### ISSUE THREAD

**Issue by jianzhichun** [marklogic/mlxprs#3]

**Comment by mikrovvelle** [comment]
Could you clarify please?

**Comment by jianzhichun** [comment]
Do we have marklogic-api association function?
Just when we type "cts:", it will recommend a list like ['cts:search' ...]

**Comment by mikrovvelle** [comment]
Ok, as in code-completion or auto-suggest. Yes, this is the next feature I'm working on. I'm going to change the name of this issue to reflect that unless you have any objections.

**Comment by mikrovvelle** [comment]
Sorry, I should've closed this back at 0.4.0's release. Doing it now.
