### ISSUE TITLE
https for JS debug adapter

### ISSUE THREAD

**Issue by zzzwan** [marklogic/mlxprs#30]
JS debug adapter needs ssl support

**Comment by mikrovvelle** [comment]
Question (probably for @jmakeig ): can we close this with the "all or nothing" approach to SSL. This would mean that the user needs SSL on both the debug server and app server, or cleartext on both. And if it's self-signed SSL on both, they would need to use the same CA location.

Should we add the two separate config items for the MVP, or release it simpler and see if anyone needs the more complex setup?

**Comment by jmakeig** [comment]
Yes, I think all or nothing is fine. An an early local development environment, I’d suspect nothing. In a more real or production environment, I’d expect everything to run over HTTPS. 

Let’s start with one config and see how far that gets us.

**Comment by mikrovvelle** [comment]
Then this one is done.
