### ISSUE TITLE
Document JavaScript debugging

### ISSUE THREAD

**Issue by jmakeig** [marklogic/mlxprs#31]
Update the README with a getting started guide quickly covering the “why” and the “how”, including the configuration options and a screenshot showing the debugger in action. Also include a link to MarkLogic documentation about required privileges.

**Comment by zzzwan** [comment]
@jmckean17 Hi Jane, could you take a look of the doc at https://github.com/marklogic/mlxprs/blob/sjsdbg/client/JSDebugger/README.md

**Comment by jmakeig** [comment]
@zzzwan and @jmckean17, I think we need to merge that content into the main README. This what shows up at https://marketplace.visualstudio.com/items?itemName=mlxprs.mlxprs. 

Pinging @mikrovvelle to make sure this is the right approach.

**Comment by mikrovvelle** [comment]
That's right, the top-level readme is the only one that you see on the marketplace.

If debugging instructions get too in-depth for one document, we could leave a brief summary of "getting started" debugging in the top readme, and then link to a dedicated one for debugging.

**Comment by zzzwan** [comment]
@jmakeig @mikrovvelle Do we have a decision of where to put the js debugger readme? Copy the content over to the main README or have a reference/link there?

**Comment by mikrovvelle** [comment]
We could just assign this one to me. I’ll try to put a succinct summary in the top-level readme, and then decide if and how much content should go in the sjsdbg one. Any objections?

**Comment by zzzwan** [comment]
No objection

**Comment by mikrovvelle** [comment]
Ok, thanks. May re-assign it back later when ready for review.

**Comment by jmckean17** [comment]
I'm wrapping up doc bugs for the 10.0-4 server release and will be able to focus on this early next week. Let me know if that will be an issue. Thanks!

**Comment by mikrovvelle** [comment]
Reässigned to @jmckean17 for review. On the sjsdbg branch: I've taken the debug setup documentation out of sjsdbg/readme and put it into our top-level readme. I tried to tighten it up a little too.

Please close the issue if it looks good, or Slack me if not.

**Comment by jmckean17** [comment]
Publishing the 10.0-4 docs today or tomorrow, then I can focus on this. Thanks.

**Comment by jmckean17** [comment]
Hi, the 10.0-4 docs are published and I can focus on this now. Can you send me the link to the content you want me to look at? It seems like there's more than one link. Thanks!

**Comment by jmckean17** [comment]
Apologies in advance for the newbee question: What is the most efficient way for me to edit the README? I'm looking at the README here: https://github.com/mikrovvelle/mlxprs. Thanks!

**Comment by mikrovvelle** [comment]
No worries. Go here: https://github.com/mikrovvelle/mlxprs/blob/sjsdbg/README.md 
This is the README version that needs your review (it will replace the current one, which is where your link points). You should be able to edit it directly on the page—there's a pencil icon, upper right relative to the text.

**Comment by jmckean17** [comment]
So when I have edited the copy, I click commit and create a pull request? Is that correct? I'm modifying the wording, so I assume you'll review when you review the pull request.

**Comment by mikrovvelle** [comment]
Yes, click "commit". You don't need to create a pull request. I'll just review your edits on the sjsdbg branch.

**Comment by jmckean17** [comment]
Do we have a screenshot of the debugger in action to add? And should we add a section on the required privileges? (What are the required privileges?) I'm not sure where we would want to like to the server docs. Suggestions?

**Comment by mikrovvelle** [comment]
Privileges are documented: https://github.com/mikrovvelle/mlxprs/blob/sjsdbg/README.md#required-privileges-for-eval-and-debugging

We do have a screenshot describing the interactive "attach" debugging mode in https://github.com/mikrovvelle/mlxprs/blob/sjsdbg/README.md#attach. Is there a specific point we need to additional screenshots to get across?

**Comment by jmckean17** [comment]
I've been looking at an earlier version of the debugger. D'oh! I didn't see the screenshot or the permissions. I will edit this version and then click commit. :-)

**Comment by jmckean17** [comment]
I have committed my changes.

**Comment by mikrovvelle** [comment]
Thanks, looks great!
