### ISSUE TITLE
Document developer set-up and test instructions in CONTRIBUTING

### ISSUE THREAD

**Issue by jmakeig** [marklogic/mlxprs#42]

**Comment by jmakeig** [comment]
As an mlxprs developer—_not_ user—I need to be able to easily get my dev environment running from source code.

**Comment by jmakeig** [comment]
Note that you need to run `npm install` in `/server` in addition to the project root. See #43.

**Comment by jmakeig** [comment]
Then from the Debug icon in the activity bar (left nav, by default), select “Launch Extension” from the drop-down and click the green play button. This will launch a new VS Code instance with the mlxprs instance compiled from source. Open the project that you want to debug from there.

**Comment by jmakeig** [comment]
Next: debugging the debugger.

**Comment by rjrudin** [comment]
Closing as we've improved this a bunch
