### ISSUE TITLE
Launch configuration labels

### ISSUE THREAD

**Issue by jmakeig** [marklogic/mlxprs#44]
* MarkLogic: Evaluate Current JavaScript Module
* MarkLogic: Attach to Remote JavaScript Request

And then if/when we implement XQuery debugging, `s/JavaScript/XQuery/` above.

**Comment by jmakeig** [comment]
Does this sound reasonable, @mikrovvelle?

**Comment by mikrovvelle** [comment]
Yep, sounds fine to me
