### ISSUE TITLE
Update developer.marklogic.com

### ISSUE THREAD

**Issue by jmakeig** [marklogic/mlxprs#49]
https://developer.marklogic.com/code/mlxprs/

- [x] Announce debugging support
- [x] De-emphasize “mlxprs”
- [x] Change URL (but don’t forget a redirect for SEO)
- [x] Point to the [Marketplace landing page](https://marketplace.visualstudio.com/items?itemName=mlxprs.mlxprs), not GitHub

**Comment by jmakeig** [comment]
Ping @TrinhML.

**Comment by jmakeig** [comment]
[As of 2020-04-17](https://developer.marklogic.com/code/mlxprs/): <img width="727" alt="image" src="https://user-images.githubusercontent.com/176233/79597125-96b33c80-8096-11ea-96fc-18ddaac43350.png">

**Comment by jmckean17** [comment]
Justin, do you want to mention Data Hub in this blurb? In Greg's edits to the marketplace and my edits to the README, we used the wording "The MarkLogic Visual Studio Code extensions allows you to run JavaScript and XQuery (*.sjs, *.mjs, *.xqy) code against a MarkLogic Data Hub or MarkLogic database." Would you want to use that here as well?

**Comment by jmakeig** [comment]
Can we change the URL to https://developer.marklogic.com/code/marklogic-vscode and redirect here from https://developer.marklogic.com/code/mlxprs/?

# MarkLogic Extension for Visual Studio Code 

_Develop, run, and debug code for MarkLogic in the popular VS Code IDE_

[Visual Studio Code](https://code.visualstudio.com) is a free, cross-platform code editor and development tool from Microsoft. The free, open-source **MarkLogic extension for VS Code** integrates MarkLogic in the cloud or on your laptop into this modern development environment.

Features:

* Syntax highlighting and IntelliSense for MarkLogic Server-Side JavaScript and XQuery
* Interactive debugging of JavaScript running in Data Hub Service or MarkLogic, including attaching to in-flight requests and inspecting live variables (_XQuery coming soon._)
*  Real-time query evaluation of JavaScript or XQuery against a live Data Hub Service or MarkLogic instance

_JavaScript debugging requires version 2.0.0+ of the MarkLogic extension and [MarkLogic 10.0-4+](https://developer.marklogic.com/products/marklogic-server/10.0)._

[Install from the VS Code marketplace](https://marketplace.visualstudio.com/items?itemName=mlxprs.mlxprs)

**Comment by jmakeig** [comment]
Note, that Microsoft uses “VS Code”—with a space—when abbreviating “Visual Studio Code”, _not_ “VSCode”—no space.

**Comment by jmakeig** [comment]
Done: https://developer.marklogic.com/code/vscode/
Thanks, @TrinhML.
