### ISSUE TITLE
Add a link to the Marketplace to the GitHub project

### ISSUE THREAD

**Issue by jmakeig** [marklogic/mlxprs#53]
Can you please add the [marketplace landing page](https://marketplace.visualstudio.com/items?itemName=mlxprs.mlxprs) to the top-level config of the GitHub project?

**Comment by mikrovvelle** [comment]
Now linked in the top-level *README*. If that's what you meant, go ahead and close this. Otherwise Slack me and we can probably fix it quick.

**Comment by jmakeig** [comment]
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/176233/79772864-7e852c80-82e5-11ea-8e75-6b3fe797b3e3.png">

Like this from the project settings.

**Comment by mikrovvelle** [comment]
Gotcha. Done.
