### ISSUE TITLE
Pre-populate the [dis]connectServer server selection dialog

### ISSUE THREAD

**Issue by mikrovvelle** [marklogic/mlxprs#54]
As a user, when I execute the connectServer command, I should be presented with a list of app servers available in my MarkLogic instance.

Ideally, the list should be responsive like other command-palette interactions in VS Code. E.g. if I want "data-hub-STAGING", I should be able to type "<kbd>s</kbd> <kbd>t</kbd> <kbd>a</kbd> <kbd>enter</kbd>" to quickly connect.

Currently, I have to type out exactly "data-hub-STAGING" with no auto-complete or other UI assistance. It's just, too daunting.

siblings: #45 and #46

**Comment by jmakeig** [comment]
Is this something we could put in the launch config? Seems like the ability to specify it dynamically is a corner case, not the primary one. Also, in DHS these names are _fixed_ and thus we should make the operational stack app server the default.

**Comment by BillFarber** [comment]
This is being implemented and tracked internally to MarkLogic:
https://project.marklogic.com/jira/browse/DEVEXP-350
