### ISSUE TITLE
Make SJS debug server port configurable

### ISSUE THREAD

**Issue by mikrovvelle** [marklogic/mlxprs#55]
There are likely situations where the user will not be running the SJS debug server on port 8002, or it will be re-mapped to a different port for whatever reason. This should be configurable, but still default to 8002.

**Comment by paxtonhare** [comment]
Just ran into this.

**Comment by brent-hartwig** [comment]
Customer using non-standard ports just hit this as well

**Comment by rjrudin** [comment]
Closing as dupe of #97
