### ISSUE TITLE
Crossing an XQuery eval/invoke boundary

### ISSUE THREAD

**Issue by jmakeig** [marklogic/mlxprs#60]
What do we expect the behavior of the debugger to be when trying to debug a request that drops into XQuery? For example, for historical reasons, Data Hub flows and REST Client API Resource Service Extensions are bootstrapped from XQuery, even if the user serviceable code is written in JavaScript. 

I wouldn’t expect the debugger to seamlessly cross over this boundary today. What are our options? 

1. Switch back and forth between interactive XQuery and JavaScript debugging in the same request (I don’t know if that’s even feasible)
2. Continue running the request, but step over any XQuery (Could JavaScript debugging be re-entrant later in the request?)
3. Cleanly abort the request with a sensible message when it tries to cross the XQuery boundary. 

The above is ordered by desirability, descending, but also by complexity/infeasibility. Are there other options? What am I missing?

In the near term and also more generally, I’d suggest extracting the JavaScript from a Data Hub step or a REST Client API Extension into its own library module and debugging it from a unit test (or bootstrap main module). I don’t think we want to encourage debugging framework code in the first place.

**Comment by jmakeig** [comment]
In the very short term, we need to characterize what happens when

1) Debugging a request that starts with an XQuery environment
2) JavaScript evals/invokes XQuery

Are there other scenarios we should characterize?

**Comment by zzzwan** [comment]
Our JS debugger does not have the ability to step through xquery. 
For 1), a user could only run that XQuery code in normal mode, the invoked JS modules will then be paused. He can then 'attach' to the paused modules. Only at this time should JS debugger step in.
2) A user can step over the line evaling/invoking, but not step into it.

**Comment by jmakeig** [comment]
For 2 above, the current behavior is to step over. (Stepping into would be a new feature and not likely something we’ll ever do.)

Attach should enable as soon as you enter the JavaScript context, even if that’s an eval/invoke from XQuery. Need to verify this and add to database and mlxprs tests.

**Comment by jmakeig** [comment]
Once we verify this behavior in a test, the scope of work here then is to document this behavior—probably just a sentence or two in the README.
