### ISSUE TITLE
Unconfirmed breakpoints appear confirmed at start of debugging

### ISSUE THREAD

**Issue by mikrovvelle** [marklogic/mlxprs#63]
In debugging, if you set the breakpoints before you launch or attach the debugger, the breakpoints appear confirmed in VS Code (red). However, they don't actually get set in MarkLogic.

This leads to the following behavior:

1. Set some breakpoints in the module you're about to debug.
2. Start the debugger. It stops at the first line of the module.
3. Hit 'continue'
4. Query completes having ignored what you thought were breakpoints that would stop execution.

Workaround is to set any breakpoint _after_ the debugger has started. Then all of the breakpoints will get set in MarkLogic.

Once the debugger starts, the breakpoints should appear unconfirmed (hollow-grey) until they are set on MarkLogic, and then appear red.

To fix: 
- JavaScript breakpoints always appear confirmed
- XQuery breakpoints appear confirmed if they were set before launch, but appear correctly confirmed/unconfirmed after doing the workaround

**Comment by zzzwan** [comment]
#75 passed integration test, close for now
