### ISSUE TITLE
Eval bug

### ISSUE THREAD

**Issue by jmakeig** [marklogic/mlxprs#64]
Eval blocks the debugger. (Internal ref: 54891)

**Comment by jmakeig** [comment]
MarkLogic dependency addressed in 10.0-4.2

**Comment by jmakeig** [comment]
@zzzwan please close as appropriate. A pointer to the test that tickles this would be good too.

**Comment by zzzwan** [comment]
Closing.
The tests related are `Testing sjs/xqy boundary in eval/invoke` under debugger test
