### ISSUE TITLE
Automated tests against DHS

### ISSUE THREAD

**Issue by jmakeig** [marklogic/mlxprs#65]
Run automated testing against a DHS instance. We need to think about the scenario where extension capabilities rely on _new_ database functionality and plan for infrastructure to support testing against pre-release versions.

This is related to, but not dependent on the extensive testing that’s performed against the database. The focus here is on the last mile and integration testing.

**Comment by jmakeig** [comment]
Related to #19

**Comment by jmakeig** [comment]
There is an existing model with mlcp. This should be the same pattern.

**Comment by zzzwan** [comment]
Tried connecting the debugger with DHS and get permission error. Seems debug privileges are not added for DHS roles.

**Comment by rjrudin** [comment]
Not likely to ever do, though we will fix bugs where mlxprs cannot connect to DHS
