### ISSUE TITLE
Unify config 'path' meaning for SJS and XQY debugging

### ISSUE THREAD

**Issue by mikrovvelle** [marklogic/mlxprs#66]
SJS debugging uses `path` in the launch config to do two different things:

1. in 'launch' mode, it points to the file representing the JS query being run.
2. in 'attach' mode, it points to the local modules root, for mapping ML modules to the local project

XQY uses `root` for the equivalent of item 2 in both launch and attach modes, and `program` for the equivalent of item 1.

Since 'path' is kind of ambiguous in this context anyway, I think we should use the XQY root/program convention in SJS.

**Comment by jmakeig** [comment]
What is the impact to the user? Do these concepts only show up in the mlxprs config or would this require backend changes to MarkLogic as well?

**Comment by mikrovvelle** [comment]
Pretty low user impact: users would need to change the key-name from:
- "path" to "program" for launch configurations, or
- "path" to "root" for attach debug configurations.

VS Code has intellisense in the `launch.json` files, so old configuration keys would get flagged with yellow squigly underlines, and they'll have autocomplete and hover tips to help them get it right.

This is all mlxprs/VSC internal. No change to MarkLogic would be needed.

**Comment by jmakeig** [comment]
I agree we should do this. Does VS Code have the ability to flag a property as _deprecated_? This would be a breaking change.

**Comment by mikrovvelle** [comment]
Not explicitly, but effectively. We can nudge users in the right direction either gently or more forcefully. Most forceful would be to just make the whole switch in one update.

More gently, we could have the config logic cascade the config keys (use either key, new overrides old) for an interim period of versions. The old field could be tagged with a description, so the user would see it in a tooltip.

<img width="338" alt="Screen Shot 2020-05-27 at 10 24 39" src="https://user-images.githubusercontent.com/21420/82995840-6f8c4b00-a004-11ea-9556-eb9b05ee1fe2.png">

We could also throw up a warning or error message at the beginning of a debug session, if the old key is still present in the launch config.

**Comment by mikrovvelle** [comment]
Closing as part of 3.1.0
