### ISSUE TITLE
Debugger entering REST extension code

### ISSUE THREAD

**Issue by mikrovvelle** [marklogic/mlxprs#68]
If you attach to a query that comes in through a REST extension, the debugger will navigate through server-side modules that are most likely not in your local project. We should be able to handle this, either using a documented workaround (at the very least), or actually streaming the module code into VS Code (at most).

**Comment by jmakeig** [comment]
Isn’t this fundamentally the same issue as #61? Are there other examples of debuggers that stream the code being debugged? I don't know if I’ve ever seen that in action.

**Comment by mikrovvelle** [comment]
It's not usual to have modules used by the REST extension logic directly in the local project. So I think this case is different in that module streaming would be the most straightforward UX to address it, whereas #61 is more about better mapping of modules you _do_ have locally.

I don't have an example from another debugger, but we may be able to use the DocumentContentProvider API to do this. Eg.

1. Debugger gets a module URI that doesn't have a mapped local file.
2. Debugger process sends missing module URI to back VS Code process.
3. VS Code queries modules database for URI, shows results in read-only buffer using DocumentContentProvider.
4. (hopefully) the debugger process can use the given module URI to navigate to its intended breakpoint.

Steps 1-3 are straightforward. I can research whether 4 would work.

**Comment by jmakeig** [comment]
> It's not usual to have modules used by the REST extension logic directly in the local project. 

Are you talking about user code or framework code? I’d agree on the latter. That’s like stepping into the code from a class imported from a third-party JAR in a Java project. I would expect to have all of the _user_ source code available locally, though, including libraries. What am I misunderstanding? 

The JAR use case is actually an illustrative one here. If I recall correctly, you can map a source directly to an imported JAR. When you do that the debugger can interactively step through third-party code. Otherwise it treats it as a black box and steps over it. From the IDE’s perspective, though, all of the code is “local”, it’s not being dynamically streamed.

**Comment by mikrovvelle** [comment]
I mean the framework code, not the user code. The server-side XQuery `dbg:` functions step over ML-internal functions, but not code from the REST extension framework, as I witnessed today.

I agree with the JAR example. That's pretty much what I had in mind. Just instead of decompiling a JAR or fetching a source package in the background, we call `fn:doc()` on the modules database.

**Comment by jmakeig** [comment]
In the JAR case, though, you don’t _decompile_. IDEs have a facility to map the uncompiled source code to the JAR, like a source map in the browser. Maven can even automatically download the source code for you as part of its dependency management lifecycle. 

> The server-side XQuery dbg: functions step over ML-internal functions, but not code from the REST extension framework, as I witnessed today.

By “ML-internal functions” you mean built-ins, like `cts:search()`? If so, stepping over them is the expected behavior; those are implemented in C++.

**Comment by mikrovvelle** [comment]
That makes sense. The general case is being able to show source modules which the debugger can access server-side, but aren't available locally. Attaching to a REST extension query is just a specific case that exposes this need.

'Decompiling' is what IDEA calls it when you step into a library JAR without having the full source, but it sounds like what you're describing (it also offers a 'Download Sources' button when you're looking at the 'decompiled .class file' in the debugger). In any case, it's a good example of fetching some extra content behind the scenes and showing it to the debugger read-only.

**Comment by jmakeig** [comment]
How would you set a breakpoint in streamed code? Only during an active session? I guess I don’t really understand the interaction we’re going for here. I’m OK with stepping over framework code. That’s really no different than (C++) built-ins.

**Comment by mikrovvelle** [comment]
On a branch: https://github.com/mikrovvelle/mlxprs/tree/moduleStream

Under the covers, VS Code shows documents using an internal map of URI ⇒ content. You can provide your own content for a given URI scheme by implementing a `TextDocumentContentProvider` for it.

This is how we show query results: we 'provide' the content for URIs with the `mlquery:` scheme. When we tell VSCode to open one of our URIs (e.g. `mlquery://localhost:8010/my/local/project/ad-hoc-query.sjs` or `mlquery://localhost:8010/untitled.untitled`), it refers to our implemented provider for the `mlquery` scheme, and returns the correct content as the response to the query.

Now I've added a provider for `mlmodule`. This simply retrieves the module at the given URI path out of the ML modules database. So you can guess what to expect if we ask VS Code to open the URI `mlmodule://localhost:8010/data-hub/4/dhf.sjs`.

The VS Code debugger uses these URIs to figure out how to display the debug cursor in the stack. Up until now, we've uses filesystem URIs. But since we now have an `mlmodule:` URI scheme, we can use this when the local filesystem URI isn't available.

**Comment by mikrovvelle** [comment]
It's even easier than I thought. The VSC debugger API has a `sourceRequest` function call which we can override, and fetch the module contents from MarkLogic in the background (if the module is not present locally). It's implemented now on the branch.
