### ISSUE TITLE
Handling of non-existing file

### ISSUE THREAD

**Issue by zzzwan** [marklogic/mlxprs#70]
Currently, JS debugger just raise an error message for non-existing file, which will be annoying when debugging with DHS. Need to have a mechanism to mute these error messages

**Comment by jmakeig** [comment]
How does this relate to the streaming work @mikrovvelle has been doing in #68?

**Comment by zzzwan** [comment]
Yeah, I think streaming should handle this #68

**Comment by jmakeig** [comment]
Can you please coördinate on an approach with @mikrovvelle?

**Comment by mikrovvelle** [comment]
@zzzwan Take a look at the [moduleStream](https://github.com/mikrovvelle/mlxprs/tree/moduleStream) branch. Have you started on this? If not, we can probably re-use most of the streaming implementation from there. Just need to use hook it into the `sourceRequest` function override for `LoggingDebugSession`.

Try me on Slack if you have any questions.

**Comment by zzzwan** [comment]
@jmakeig Need some clarification. We have a closed issue deciding not to do streaming at the time. Do we now plan to add it?

**Comment by jmakeig** [comment]
Is there a test that validates this? When that’s confirmed we can close this.

**Comment by zzzwan** [comment]
Test in suite 'Issue 70'

**Comment by mikrovvelle** [comment]
Passes test consistently. Will be added to imminent 3.1.0 release.
