### ISSUE TITLE
JavaScript debugger hangs sometimes

### ISSUE THREAD

**Issue by jkerr5** [marklogic/mlxprs#76]
There seems to be some sort of race condition that happens if you "continue" quickly after starting to debug a request. It also seems to happen when clicking step over quickly over and over as well.

This results in requests stuck on the task server as well as the VS code debugger in a state where the the only option is to cancel the request.

To reproduce
1. create a SJS module
2. set one or more breakpoints
3. launch it via the debugger "Evaluate Current JavaScript Module" launch configuration
4. quickly hit the "continue" button after launching

It may take multiple tries to get it to happen. It also may be easier to reproduce if you are running against a MarkLogic instance with less compute resources so it responds slower.

**Comment by zzzwan** [comment]
@jkerr5 Hello, there is one bug in extension that doesn't timely flip the UI while request changed from stop to running. By addressing this, the debug buttons should be grayed out in 'running' state to prevent multiple clicking.

**Comment by zzzwan** [comment]
We also found one potential race condition in server, but I suspect it's more likely the client bug causing this issue.

**Comment by zzzwan** [comment]
We can close this issue for now and ship the extension fix in next release. If the problem persists, we'll work on server fix.

**Comment by zzzwan** [comment]
Fix submitted. Close for now. Integration test needs to be updated
