### ISSUE TITLE
Debugging variables in module scope

### ISSUE THREAD

**Issue by nupoork** [marklogic/mlxprs#77]
Adding a watch for variables in module scope while debugging ES2015 modules sometimes yields Reference errors. This manifests for variables that are defined in module scope and are not used in any functions. The workaround for debugging and inspecting such variables is to have them used in a function in that module (simply calling the variable in a function works). Another workaround available is to have an eval() statement in the module program. This behavior could be reproduced in Node.js as well in a version (v10.8.0) that uses the same V8 version as MarkLogic 10 does. It is suspected that the bug might be related to heap vs. stack allocation of variables in V8 engine.

**Comment by zzzwan** [comment]
d4885dc1adad74395392eec57a57f5bf930de1dc
