### ISSUE TITLE
Unable to step thru file after attaching to remote server on Windows

### ISSUE THREAD

**Issue by freeweel** [marklogic/mlxprs#81]
Versions:  Windows 10 Pro v1909, ML 10.0-4, VSCode 1.47.3, mlxprs 3.0.4

[User.zip](https://github.com/mikrovvelle/mlxprs/files/5070584/User.zip)

This was demonstrated via WebEx to Justin Makeig and Zhichun Wan on 8/13/2020
I have a simple JS file that I used that is present on the file system and exists in the MODULES db.

To reproduce:
1.  Connect to debug server (connect worked)
2.  Start remote process using curl
3.  Select "Attach to debug request"
4.  Select the running process from the dropdown
5.  Debugger appears to start and highlights first line of JS file
6.  I am unable to do anything at that point.  Unable to step over, step into, or run to completion.

I have attached my launch and settings configs

**Comment by jmakeig** [comment]
@zzzwan wasn’t able to reproduce this in multiple Windows environments. @freeweel if you have any more info please re-open this bug or file a new one.
