### ISSUE TITLE
Support stepping through xdmp eval and invoke

### ISSUE THREAD

**Issue by zzzwan** [marklogic/mlxprs#82]
After 10.4-2, server will support stepping through xdmp.eval() and xdmp.invoke(). 

So far, the debug adapter supports xdmp.invoke().

However, for xdmp.eval(), the url of all eval scripts are empty string, which makes differentiation between them problem.

**Comment by jmakeig** [comment]
I’m assuming this is an enhancement to stepping over evaled/invoked code, not a fix where the debugger barfs on evaled/invoked code. If so, let’s push this out of 3.1.0 in the interest of shipping that sooner.

**Comment by yasht2010** [comment]
Enhancement to step through invoked code, specifically a data hub step interceptor - Read more on how step interceptor is invoked - https://github.com/marklogic/marklogic-data-hub/tree/develop/examples/step-interceptors/
