### ISSUE TITLE
ignore insecure SSL connections

### ISSUE THREAD

**Issue by khashayar** [marklogic/mlxprs#85]
I'm working on an environment that the ssl certificate attached to the app server does not contain the actual hostname, which makes the certificate invalid.

Is it possible to add a configuration option to ignore insecure SSL connections, something similar to `-k` for cURL?

**Comment by mikrovvelle** [comment]
It looks like this would require getting the MarkLogic node.js client to ignore certificate/host check. I don't see a straightforward way to do it, so we might need an RFE for it.

**Comment by khashayar** [comment]
In the ML Node.js [docs](https://docs.marklogic.com/jsdoc/marklogic.html), for the `ssl` option, it reads:

> whether the REST server uses SSL; when true, the connection parameters can include the supplemental HTTPS options specifiable for the node.js tls.connect() function.

And based on Node.js [docs](https://nodejs.org/api/tls.html#tls_tls_connect_options_callback):

> `rejectUnauthorized` <boolean> If not false, the server certificate is verified against the list of supplied CAs. Default: `true`.

So I guess if the `rejectUnauthorized` is specified, alongside `ssl: true`, it gets passed to Node.js and as a result ignores insecure SSL.

**Comment by mikrovvelle** [comment]
Good catch. I missed this in the node docs. It looks like we just need to expose `rejectUnauthorized` and allow it to be set to false.

**Comment by rjrudin** [comment]
This apparently was closed in 3.2.0
