### ISSUE TITLE
inline mlxprs settings configuration

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/mlxprs#9]
I have mlxprs installed with the default settings.
I would like the ability to override those settings in my javascript file so I can better stay in my editor and support multiple projects.

Therefore my `database` settings is set to `Documents`.
My code could have the following comment block
```
/* Settings:mlxprs
  mlxprs.database='data-hub';
  mlxprs.username='some-disadvantaged-user';
  mlxprs.password='shillingForADaysWork';
*/
```

**Comment by mikrovvelle** [comment]
Is this needed above and beyond the capability of VS Code to override your User settings with Workspace-specific settings, as described in the link?

https://code.visualstudio.com/docs/getstarted/settings

Namely this bit:

> VS Code provides two different scopes for settings:
> - User Settings - Settings that apply globally to any instance of VS Code you open.
> - Workspace Settings - Settings stored inside your workspace and only apply when the workspace is opened.
>
> Workspace settings override user settings.

**Comment by prestonmcgowan** [comment]
Even more granular? On a per execution level.
Runtime configuration.

**Comment by mikrovvelle** [comment]
Ok. Makes sense as a new feature. I was thinking of something similar to help test out DHF harmonization modules as well.

**Comment by mikrovvelle** [comment]
Going to be merging the feature soon. The override syntax will be slightly different than your example, but it will do what you want.

Overrides are:

 - In a JS block comment
 - the first line of the block comment must include the string 'mlxprs:settings'
 - the rest of the comment must be a valid JSON object
 - the keys of the JSON object are the client parameters you wish to override

E.g.

```js
/* mlxprs:settings
  {
    "host": "other-server.local",
    "port": 8010,
    "contentDb": "data-hub-FINAL"
  }
*/
// here comes the actual query...
```

If the JSON parsing fails, you'll get an error message from VS Code, and then we'll fall back and fire the query at the non-overridden configuration.

Sound good @prestonmcgowan ?

**Comment by prestonmcgowan** [comment]
Sounds great.

Thank you.

**Comment by mikrovvelle** [comment]
Released in 1.1.0. I'll leave this open for bugs for a day, then close it.

**Comment by mikrovvelle** [comment]
@jmakeig how would this be any more brittle than the existing way of managing client connection parameters through VS Code's settings?

**Comment by jmakeig** [comment]
I think managing connections via user preferences is the problem. I could imagine a sidebar in the UI with tree of clusters and databases, allowing you to select the context (like in Query Console) or even browse.
