### ISSUE TITLE
Eval against DHS instance not working with latest VS code release

### ISSUE THREAD

**Issue by yasht2010** [marklogic/mlxprs#96]
See issue: https://github.com/marklogic/node-client-api/issues/568

**Comment by mtcotton** [comment]
Fix is available in the node-client dev branch and is ready for testing

https://github.com/marklogic/node-client-api/issues/568#issuecomment-827800924

**Comment by rjrudin** [comment]
This may just need some research to see if it's a) working already, or b) we just need to bump up the dependency of the node-client-api.

**Comment by rjrudin** [comment]
@bshalke will verify

**Comment by mitchshepherd** [comment]
This ticket was addressed via a Node Client API v2.7 bug fix
